export default [
  {
    "id": "pn_08",
    "type": "prenatal",
    "gestationalWeek": 8,
    "title": "Embryonic development begins",
    "weeklyFact": "The embryo is about the size of a raspberry.",
    "description": "Major organs and body systems begin to form."
  },
  {
    "id": "pn_12",
    "type": "prenatal",
    "gestationalWeek": 12,
    "title": "Fetal stage begins",
    "weeklyFact": "The fetus is about 2.5 inches long.",
    "description": "Facial features are developing, and the fetus can make movements."
  },
  {
    "id": "pn_16",
    "type": "prenatal",
    "gestationalWeek": 16,
    "title": "Movement and growth",
    "weeklyFact": "The fetus is about 4.5 inches long.",
    "description": "The fetus can move, and gender can be determined by ultrasound."
  },
  {
    "id": "pn_20",
    "type": "prenatal",
    "gestationalWeek": 20,
    "title": "Hearing develops",
    "weeklyFact": "The fetus is about 6 inches long.",
    "description": "The fetus can hear sounds and may respond to them."
  },
  {
    "id": "pn_24",
    "type": "prenatal",
    "gestationalWeek": 24,
    "title": "Lungs developing",
    "weeklyFact": "The fetus is about 8 inches long.",
    "description": "Lungs are developing, increasing chances of survival if born early."
  },
  {
    "id": "pn_28",
    "type": "prenatal",
    "gestationalWeek": 28,
    "title": "Brain growth accelerates",
    "weeklyFact": "The fetus is about 10 inches long.",
    "description": "The brain is rapidly developing, and the fetus can open its eyes."
  },
  {
    "id": "pn_32",
    "type": "prenatal",
    "gestationalWeek": 32,
    "title": "Rapid growth phase",
    "weeklyFact": "The fetus is about 11 inches long.",
    "description": "Lungs are maturing, and the fetus is gaining weight quickly."
  },
  {
    "id": "pn_36",
    "type": "prenatal",
    "gestationalWeek": 36,
    "title": "Full term readiness",
    "weeklyFact": "The fetus is about 12 inches long.",
    "description": "The fetus is ready for birth, with all organs developed."
  },
  {
    "id": "m_001",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Smiles at people",
    "description": "Shows a social smile in response to caregivers.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_002",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Makes cooing sounds",
    "description": "Vocalizes with coos and gurgling sounds.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_003",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Holds head steady",
    "description": "Can hold head up steadily when on tummy.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_004",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Pushes up on arms",
    "description": "Pushes up on forearms when lying on tummy.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_005",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Reaches for objects",
    "description": "Reaches out to grasp nearby objects.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_006",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Follows objects with eyes",
    "description": "Tracks moving objects with eyes.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_007",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Recognizes familiar people",
    "description": "Shows recognition of familiar faces and voices.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_008",
    "type": "postnatal",
    "ageLowerDays": 30,
    "ageUpperDays": 90,
    "ageLabel": "1–3 months",
    "title": "Responds to sounds",
    "description": "Turns head toward sounds and voices.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_009",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Rolls over",
    "description": "Rolls from tummy to back or back to tummy.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_010",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Sits without support",
    "description": "Can sit upright without support for short periods.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_011",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Babbles",
    "description": "Makes babbling sounds like 'ba-ba' or 'ma-ma'.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_012",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Laughs",
    "description": "Laughs out loud at playful interactions.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_013",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Reaches for objects",
    "description": "Reaches and grasps objects accurately.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_014",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Passes objects between hands",
    "description": "Transfers objects from one hand to the other.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_015",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Responds to name",
    "description": "Turns when their name is called.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_016",
    "type": "postnatal",
    "ageLowerDays": 120,
    "ageUpperDays": 180,
    "ageLabel": "4–6 months",
    "title": "Shows interest in mirror",
    "description": "Looks at and interacts with their reflection in a mirror.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_017",
    "type": "postnatal",
    "ageLowerDays": 210,
    "ageUpperDays": 270,
    "ageLabel": "7–9 months",
    "title": "Crawls",
    "description": "Moves forward on hands and knees.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_018",
    "type": "postnatal",
    "ageLowerDays": 210,
    "ageUpperDays": 270,
    "ageLabel": "7–9 months",
    "title": "Stands holding on",
    "description": "Pulls up to stand while holding onto furniture.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_019",
    "type": "postnatal",
    "ageLowerDays": 210,
    "ageUpperDays": 270,
    "ageLabel": "7–9 months",
    "title": "Says 'mama' or 'dada'",
    "description": "Uses simple words to refer to parents.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_020",
    "type": "postnatal",
    "ageLowerDays": 210,
    "ageUpperDays": 270,
    "ageLabel": "7–9 months",
    "title": "Waves bye-bye",
    "description": "Waves hand to say goodbye.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_021",
    "type": "postnatal",
    "ageLowerDays": 210,
    "ageUpperDays": 270,
    "ageLabel": "7–9 months",
    "title": "Plays peek-a-boo",
    "description": "Enjoys and participates in peek-a-boo games.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_022",
    "type": "postnatal",
    "ageLowerDays": 210,
    "ageUpperDays": 270,
    "ageLabel": "7–9 months",
    "title": "Points to objects",
    "description": "Points at objects of interest.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_023",
    "type": "postnatal",
    "ageLowerDays": 210,
    "ageUpperDays": 270,
    "ageLabel": "7–9 months",
    "title": "Uses pincer grasp",
    "description": "Picks up small objects with thumb and forefinger.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_024",
    "type": "postnatal",
    "ageLowerDays": 300,
    "ageUpperDays": 365,
    "ageLabel": "10–12 months",
    "title": "Stands alone",
    "description": "Stands without holding on for a few seconds.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_025",
    "type": "postnatal",
    "ageLowerDays": 300,
    "ageUpperDays": 365,
    "ageLabel": "10–12 months",
    "title": "Takes first steps",
    "description": "Walks with support or takes independent steps.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_026",
    "type": "postnatal",
    "ageLowerDays": 300,
    "ageUpperDays": 365,
    "ageLabel": "10–12 months",
    "title": "Says 1-2 words",
    "description": "Uses simple words besides 'mama' and 'dada'.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_027",
    "type": "postnatal",
    "ageLowerDays": 300,
    "ageUpperDays": 365,
    "ageLabel": "10–12 months",
    "title": "Follows simple commands",
    "description": "Follows one-step commands like 'come here'.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_028",
    "type": "postnatal",
    "ageLowerDays": 300,
    "ageUpperDays": 365,
    "ageLabel": "10–12 months",
    "title": "Points to body parts",
    "description": "Points to eyes, nose, or other body parts when asked.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_029",
    "type": "postnatal",
    "ageLowerDays": 300,
    "ageUpperDays": 365,
    "ageLabel": "10–12 months",
    "title": "Drinks from cup",
    "description": "Drinks from a cup with help.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_030",
    "type": "postnatal",
    "ageLowerDays": 300,
    "ageUpperDays": 365,
    "ageLabel": "10–12 months",
    "title": "Eats with fingers",
    "description": "Picks up small pieces of food and eats them.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_031",
    "type": "postnatal",
    "ageLowerDays": 395,
    "ageUpperDays": 545,
    "ageLabel": "13–18 months",
    "title": "Walks well",
    "description": "Walks steadily without holding on.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_032",
    "type": "postnatal",
    "ageLowerDays": 395,
    "ageUpperDays": 545,
    "ageLabel": "13–18 months",
    "title": "Says 10-20 words",
    "description": "Uses 10-20 words, including names of familiar objects.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_033",
    "type": "postnatal",
    "ageLowerDays": 395,
    "ageUpperDays": 545,
    "ageLabel": "13–18 months",
    "title": "Uses spoon",
    "description": "Scoops food with a spoon and brings it to mouth.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_034",
    "type": "postnatal",
    "ageLowerDays": 395,
    "ageUpperDays": 545,
    "ageLabel": "13–18 months",
    "title": "Scribbles",
    "description": "Makes marks on paper with crayons.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_035",
    "type": "postnatal",
    "ageLowerDays": 395,
    "ageUpperDays": 545,
    "ageLabel": "13–18 months",
    "title": "Points to pictures",
    "description": "Points to pictures in books when named.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_036",
    "type": "postnatal",
    "ageLowerDays": 395,
    "ageUpperDays": 545,
    "ageLabel": "13–18 months",
    "title": "Follows 2-step commands",
    "description": "Follows two-step commands like 'pick up the toy and give it to me'.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_037",
    "type": "postnatal",
    "ageLowerDays": 575,
    "ageUpperDays": 730,
    "ageLabel": "19–24 months",
    "title": "Runs",
    "description": "Runs without falling often.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_038",
    "type": "postnatal",
    "ageLowerDays": 575,
    "ageUpperDays": 730,
    "ageLabel": "19–24 months",
    "title": "Kicks ball",
    "description": "Kicks a ball forward.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_039",
    "type": "postnatal",
    "ageLowerDays": 575,
    "ageUpperDays": 730,
    "ageLabel": "19–24 months",
    "title": "Says 50 words",
    "description": "Uses about 50 words.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_040",
    "type": "postnatal",
    "ageLowerDays": 575,
    "ageUpperDays": 730,
    "ageLabel": "19–24 months",
    "title": "Combines 2 words",
    "description": "Puts two words together, like 'more juice'.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_041",
    "type": "postnatal",
    "ageLowerDays": 575,
    "ageUpperDays": 730,
    "ageLabel": "19–24 months",
    "title": "Names pictures",
    "description": "Names pictures in books.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_042",
    "type": "postnatal",
    "ageLowerDays": 575,
    "ageUpperDays": 730,
    "ageLabel": "19–24 months",
    "title": "Washes hands",
    "description": "Helps wash hands.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_043",
    "type": "postnatal",
    "ageLowerDays": 760,
    "ageUpperDays": 910,
    "ageLabel": "25–30 months",
    "title": "Jumps",
    "description": "Jumps in place with both feet.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_044",
    "type": "postnatal",
    "ageLowerDays": 760,
    "ageUpperDays": 910,
    "ageLabel": "25–30 months",
    "title": "Says 200 words",
    "description": "Uses about 200 words.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_045",
    "type": "postnatal",
    "ageLowerDays": 760,
    "ageUpperDays": 910,
    "ageLabel": "25–30 months",
    "title": "Uses pronouns",
    "description": "Uses pronouns like 'I', 'you', 'me'.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_046",
    "type": "postnatal",
    "ageLowerDays": 760,
    "ageUpperDays": 910,
    "ageLabel": "25–30 months",
    "title": "Plays simple games",
    "description": "Plays simple pretend games.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_047",
    "type": "postnatal",
    "ageLowerDays": 760,
    "ageUpperDays": 910,
    "ageLabel": "25–30 months",
    "title": "Draws lines",
    "description": "Draws straight lines and circles.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_048",
    "type": "postnatal",
    "ageLowerDays": 930,
    "ageUpperDays": 1095,
    "ageLabel": "31–36 months",
    "title": "Rides tricycle",
    "description": "Pedals a tricycle.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_049",
    "type": "postnatal",
    "ageLowerDays": 930,
    "ageUpperDays": 1095,
    "ageLabel": "31–36 months",
    "title": "Says full sentences",
    "description": "Uses 3-4 word sentences.",
    "critical": true,
    "custom": false
  },
  {
    "id": "m_050",
    "type": "postnatal",
    "ageLowerDays": 930,
    "ageUpperDays": 1095,
    "ageLabel": "31–36 months",
    "title": "Dresses self",
    "description": "Helps dress and undress self.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_051",
    "type": "postnatal",
    "ageLowerDays": 930,
    "ageUpperDays": 1095,
    "ageLabel": "31–36 months",
    "title": "Plays with others",
    "description": "Plays with other children.",
    "critical": false,
    "custom": false
  },
  {
    "id": "m_052",
    "type": "postnatal",
    "ageLowerDays": 930,
    "ageUpperDays": 1095,
    "ageLabel": "31–36 months",
    "title": "Draws circles",
    "description": "Draws circles and squares.",
    "critical": false,
    "custom": false
  }
];